live_config_reload = true

[cursor]
blink_interval = 600
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
size = 17.5

[font.normal]
family = "霞鹜文楷等宽"
style = "Bold"

[window]
opacity = 0.85

[window.padding]
x = 20
y = 20

[colors.primary]
# background = '0x434b5c'
background = '0x3a4251'
