live_config_reload = true

[cursor]
blink_interval = 600
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
size = 15.7

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Semibold"

[window]
opacity = 0.85

[window.padding]
x = 20
y = 20

[colors.primary]
# background = '0x434b5c'
background = '0x3a4251'
